config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"


  resources :books, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]
  get "home/about"=>"homes#about"
  
   # ネストさせる フォローフォロワーのrouteing
  # get 'relationships/followings'
  # get 'relationships/followers'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "/search", to: "searches#search"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end
  
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<table>
   <tbody>
    <% book.book_comments.each do |book_comment| %>
     <tr>
      <td> <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br/>
       <%= link_to book_comment.user.name, user_path(user) %></td>
      <td><%= book_comment.comment %></td>
       <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy',  book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
       <% end %>
    <% end %>
     </tr>
  </tbody>
</table>